#!/usr/bin/env bash
# This script displays a list of currently running processes

# Using ps command to display processes in a user-oriented format
ps -e --forest -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --sort=start | head -n 51
