#!/usr/bin/env bash
# Manages the 'manage_my_process' script by starting, stopping, or restarting it.

command="$1"

if [ -z "$command" ]; then
	echo "Usage: $0 {start|stop|restart}"
	exit
fi

if [ "$command" == "start" ]; then
	bash ./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
	if [ -e "/var/run/my_process.pid" ]; then
		pkill -f './manage_my_process'
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running"
  fi

elif [ "$command" == "restart" ]; then
	"$0" stop >/dev/null 2>&1
	"$0" start >/dev/null 2>&1
	echo "manage_my_process restarted"

else
	echo "Usage: $0 {start|stop|restart}"
fi
