#!/bin/bash
# Script: 101-tell_the_story_of_passwd
# Description: Displays user information from /etc/passwd in a formatted way.
# Usage: ./101-tell_the_story_of_passwd

# Iterate over each line of user information retrieved by getent
getent passwd | while IFS=: read -r username password uid gid gecos homedir shell; do
    # Extract the user ID info
    userinfo=$(getent passwd "$username")

    # Parse the user ID info
    IFS=: read -r _ _ _ _ info <<< "$userinfo"

    # Print the formatted user information
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done
