#!/bin/bash
# Script: 101-tell_the_story_of_passwd
# Description: Displays user information from /etc/passwd in a formatted way.
# Usage: ./101-tell_the_story_of_passwd

while IFS=: read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < <(getent passwd)
